name: domus
description: A home automation smart application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  awesome_circular_chart: ^1.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  image_picker: ^0.8.4+11
  lottie: ^2.4.0
  provider: ^6.0.2
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_charts: ^22.1.34
  table_calendar: ^3.0.4
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_lints: ^2.0.1

  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_1024.png
  android: true
  ios: true

flutter:
  uses-material-design: true